namespace Gesdata.VF.Core.Errors
{
    internal static class AeatErrorCatalogGenerated
    {
        // Catálogo fijo versionado directamente en diccionario (código -> mensaje).
        internal static readonly System.Collections.Generic.IReadOnlyDictionary<string, string> Map =
            new System.Collections.Generic.Dictionary<string, string>(System.StringComparer.OrdinalIgnoreCase)
            {
                ["4102"] = "El XML no cumple el esquema. Falta informar campo obligatorio.",
                ["4103"] = "Se ha producido un error inesperado al parsear el XML.",
                ["4104"] = "Error en la cabecera: el valor del campo NIF del bloque ObligadoEmision no está identificado.",
                ["4105"] = "Error en la cabecera: el valor del campo NIF del bloque Representante no está identificado.",
                ["4106"] = "El formato de fecha es incorrecto.",
                ["4107"] = "El NIF no está identificado en el censo de la AEAT.",
                ["4108"] = "Error técnico al obtener el certificado.",
                ["4109"] = "El formato del NIF es incorrecto.",
                ["4110"] = "Error técnico al comprobar los apoderamientos.",
                ["4111"] = "Error técnico al crear el trámite.",
                ["4112"] = "El titular del certificado debe ser Obligado Emisión, Colaborador Social, Apoderado o Sucesor.",
                ["4113"] = "El XML no cumple con el esquema: se ha superado el límite permitido de registros para el bloque.",
                ["4114"] = "El XML no cumple con el esquema: se ha superado el límite máximo permitido de facturas a registrar.",
                ["4115"] = "El valor del campo NIF del bloque ObligadoEmision es incorrecto.",
                ["4116"] = "Error en la cabecera: el campo NIF del bloque ObligadoEmision tiene un formato incorrecto.",
                ["4117"] = "Error en la cabecera: el campo NIF del bloque Representante tiene un formato incorrecto.",
                ["4118"] = "Error técnico: la dirección no se corresponde con el fichero de entrada.",
                ["4119"] = "Error al informar caracteres cuya codificación no es UTF-8.",
                ["4120"] = "Error en la cabecera: el valor del campo FechaFinVeriFactu es incorrecto, debe ser31-12-20XX, donde XX corresponde con el año actual o el anterior.",
                ["4121"] = "Error en la cabecera: el valor del campo Incidencia es incorrecto.",
                ["4122"] = "Error en la cabecera: el valor del campo RefRequerimiento es incorrecto.",
                ["4123"] = "Error en la cabecera: el valor del campo NIF del bloque Representante no está identificado en el censo de la AEAT.",
                ["4124"] = "Error en la cabecera: el valor del campo Nombre del bloque Representante no está identificado en el censo de la AEAT.",
                ["4125"] = "Error en la cabecera: Si el envío es por requerimiento el campo RefRequerimiento es obligatorio.",
                ["4126"] = "Error en la cabecera: el campo RefRequerimiento solo debe informarse en sistemas en remisiones al endpoint del servicio a usar para la contestación a requerimientos de registros de facturación.",
                ["4127"] = "Error en la cabecera: la remisión voluntaria solo debe informarse en sistemas VERIFACTU.",
                ["4128"] = "Error técnico en la recuperación del valor del Gestor de Tablas.",
                ["4129"] = "Error en la cabecera: el campo FinRequerimiento es obligatorio.",
                ["4130"] = "Error en la cabecera: el campo FinRequerimiento solo debe informarse en sistemas No VERIFACTU.",
                ["4131"] = "Error en la cabecera: el valor del campo FinRequerimiento es incorrecto.",
                ["4132"] = "El titular del certificado debe ser el destinatario que realiza la consulta, un Apoderado o Sucesor",
                ["4133"] = "Error en la cabecera: el valor del campo RefRequerimiento no es alfanumérico.",
                ["3500"] = "Error técnico de base de datos: error en la integridad de la información.",
                ["3501"] = "Error técnico de base de datos.",
                ["3502"] = "La factura consultada para el suministro de pagos/cobros/inmuebles no existe.",
                ["3503"] = "La factura especificada no pertenece al titular registrado en el sistema.",
                ["4134"] = "Servicio no activo.",
                ["4135"] = "Esta URL no puede ser utilizada mediante GET.",
                ["4136"] = "No se ha enviado el nodo RegistroAlta o el anterior al nodo RegistroAlta no es correcto.",
                ["4137"] = "No se ha enviado el nodo RegistroAnulacion o el anterior al nodo RegistroAnulacion no es correcto.",
                ["4138"] = "Petición vacía en el XML o encoding incorrecto.",
                ["4139"] = "Servicio no habilitado en producción.",
                ["4140"] = "No puede acceder a la consulta de facturas al no estar apoderado en los trámites necesarios.",
                ["4141"] = "Acceso suspendido temporalmente. Contacte soporte verifactu@correo.aeat.es.",
                ["1100"] = "Valor o tipo incorrecto del campo.",
                ["1101"] = "El valor del campo CodigoPais es incorrecto.",
                ["1102"] = "El valor del campo IDType es incorrecto.",
                ["1103"] = "El valor del campo ID es incorrecto.",
                ["1104"] = "El valor del campo NumSerieFactura es incorrecto.",
                ["1105"] = "El valor del campo FechaExpedicionFactura es incorrecto.",
                ["1106"] = "El valor del campo TipoFactura no está incluido en la lista de valores permitidos.",
                ["1107"] = "El valor del campo TipoRectificativa es incorrecto.",
                ["1108"] = "El NIF del IDEmisorFactura debe ser el mismo que el NIF del ObligadoEmision.",
                ["1109"] = "El NIF no está identificado en el censo de la AEAT.",
                ["1110"] = "El NIF no está identificado en el censo de la AEAT.",
                ["1111"] = "El campo CodigoPais es obligatorio cuando IDType es distinto de NIF-IVA (02).",
                ["1112"] = "El campo FechaExpedicionFactura es superior a la fecha actual.",
                ["1114"] = "Si la factura es de tipo rectificativa, el campo TipoRectificativa debe tener valor.",
                ["1115"] = "Si la factura no es de tipo rectificativa, el campo TipoRectificativa no debe tener valor.",
                ["1116"] = "Debe informarse el campo FacturasSustituidas sólo si la factura es de tipo F3.",
                ["1117"] = "Si la factura no es de tipo rectificativa, el bloque FacturasRectificadas no podrá venir informado.",
                ["1118"] = "Si la factura es de tipo rectificativa por sustitución el bloque ImporteRectificacion es obligatorio.",
                ["1119"] = "Si la factura no es de tipo rectificativa por sustitución el bloque ImporteRectificacion no debe tener valor.",
                ["1120"] = "Valor de campo IDEmisorFactura del bloque IDFactura con tipo incorrecto.",
                ["1121"] = "El campo ID no está identificado en el censo de la AEAT.",
                ["1122"] = "El campo CodigoPais indicado no coincide con los dos primeros dígitos del identificador.",
                ["1123"] = "El formato del NIF es incorrecto.",
                ["1124"] = "El valor del campo TipoImpositivo no está incluido en la lista de valores permitidos.",
                ["1125"] = "El valor del campo FechaOperacion tiene una fecha superior a la permitida.",
                ["1126"] = "CodigoPais solo puede ser ES para Pasaporte (03) o No Censado (07); si No Censado (07) entonces ES.",
                ["1127"] = "El valor del campo TipoRecargoEquivalencia no está incluido en la lista de valores permitidos.",
                ["1128"] = "No existe acuerdo de facturación.",
                ["1129"] = "Error técnico al obtener el acuerdo de facturación.",
                ["1130"] = "El campo NumSerieFactura contiene caracteres no permitidos.",
                ["1131"] = "ID debe ser NIF persona física cuando IDType=No Censado (07).",
                ["1132"] = "TipoImpositivo sólo permitido para fecha <= año2012.",
                ["1133"] = "FechaExpedicionFactura no debe ser inferior a fecha actual menos veinte años.",
                ["1134"] = "FechaOperacion no debe ser inferior a fecha actual menos veinte años.",
                ["1135"] = "TipoRecargoEquivalencia sólo permitido para fecha <= año2012.",
                ["1136"] = "FacturaSimplificadaArticulos7273 solo acepta valores N o S.",
                ["1137"] = "Macrodato solo acepta valores N o S.",
                ["1138"] = "Macrodato solo debe ser S si ImporteTotal >= +-100.000.000.",
                ["1139"] = "Si ImporteTotal >= +-100.000.000 Macrodato debe ser S.",
                ["1140"] = "CuotaRepercutida y BaseImponibleACoste deben tener el mismo signo.",
                ["1142"] = "CuotaRepercutida incorrecta para BaseImponibleOimporteNoSujeto y TipoImpositivo.",
                ["1143"] = "CuotaRepercutida y BaseImponibleOimporteNoSujeto deben tener el mismo signo.",
                ["1144"] = "CuotaRepercutida incorrecta para BaseImponibleACoste y TipoImpositivo.",
                ["1145"] = "Formato de fecha incorrecto.",
                ["1146"] = "Fecha expedición anterior a fecha operación sólo si ClaveRegimen14/15 e Impuesto01,03 o vacío.",
                ["1147"] = "Si ClaveRegimen14, FechaOperacion obligatoria y posterior a FechaExpedicionFactura.",
                ["1148"] = "Si ClaveRegimen14, TipoFactura debe ser F1,R1,R2,R3 o R4.",
                ["1149"] = "Si ClaveRegimen14, NIF Destinatarios debe empezar por P,Q,S o V y estar identificado.",
                ["1150"] = "Para TipoFactura F2 sin NumRegistroAcuerdoFacturacion o sin FacturaSinIdentifDestinatarioArt61d=S suma Base+Cuota <=3000.",
                ["1151"] = "EmitidaPorTerceroODestinatario solo acepta T o D.",
                ["1152"] = "Fecha expedición no puede ser inferior al28/10/2024.",
                ["1153"] = "RechazoPrevio=X requiere Subsanacion=S.",
                ["1154"] = "NIF emisor de factura rectificada/sustitutiva no identificado.",
                ["1155"] = "Se informa bloque Tercero sin informar EmitidaPorTerceroODestinatario.",
                ["1156"] = "Para IDOtro IDType NIF-IVA (02), TipoFactura incorrecto.",
                ["1157"] = "Cupón sólo S o N; S solo si TipoFactura R1 o R5.",
                ["1158"] = "EmitidaPorTerceroODestinatario informado pero falta bloque correspondiente.",
                ["1159"] = "Se informa bloque Tercero cuando se indica Destinatario.",
                ["1160"] = "Si TipoImpositivo5% sólo TipoRecargoEquivalencia0,5 o0,62.",
                ["1161"] = "RechazoPrevio=S inválido sin Subsanacion=S.",
                ["1162"] = "Si TipoImpositivo21% sólo TipoRecargoEquivalencia5,2 ó1,75.",
                ["1163"] = "Si TipoImpositivo10% sólo TipoRecargoEquivalencia1,4.",
                ["1164"] = "Si TipoImpositivo4% sólo TipoRecargoEquivalencia0,5.",
                ["1165"] = "Si TipoImpositivo0% sólo TipoRecargoEquivalencia0% entre01/01/2023 y30/09/2024.",
                ["1166"] = "Si TipoImpositivo2% (01/10/2024-31/12/2024) sólo TipoRecargoEquivalencia0,26.",
                ["1167"] = "Si TipoImpositivo5% (>=01/07/2022 y <=31/12/2022) sólo TipoRecargoEquivalencia0,5.",
                ["1168"] = "Si TipoImpositivo5% (>=01/01/2023 y <=30/09/2024) sólo TipoRecargoEquivalencia0,62.",
                ["1169"] = "Si TipoImpositivo7,5% (01/10/2024-31/12/2024) sólo TipoRecargoEquivalencia1.",
                ["1170"] = "Si TipoImpositivo0% desde01/10/2024 sólo TipoRecargoEquivalencia0,26.",
                ["1171"] = "Subsanacion o RechazoPrevio fuera de valores permitidos.",
                ["1172"] = "NIF u ObligadoEmision nulos.",
                ["1173"] = "FechaOperacion > fecha actual solo si ClaveRegimen14/15 e Impuesto IVA(01)/IGIC(03)/vacío.",
                ["1174"] = "FechaExpedicionFactura en RegistroAnteriores incorrecta.",
                ["1175"] = "NumSerieFactura en RegistroAnterior incorrecto.",
                ["1176"] = "NIF en SistemaInformatico incorrecto.",
                ["1177"] = "IdSistemaInformatico incorrecto.",
                ["1178"] = "Error en bloque Tercero.",
                ["1179"] = "Error en bloque SistemaInformatico.",
                ["1180"] = "Error en bloque Encadenamiento.",
                ["1181"] = "CalificacionOperacion incorrecta.",
                ["1182"] = "OperacionExenta incorrecta.",
                ["1183"] = "FacturaSimplificadaArticulos7273=S sólo si TipoFactura F1,F3,R1,R2,R3,R4.",
                ["1184"] = "FacturaSinIdentifDestinatarioArt61d solo S o N.",
                ["1185"] = "FacturaSinIdentifDestinatarioArt61d=S sólo si TipoFactura F2 o R5.",
                ["1186"] = "EmitidaPorTercerosODestinatario=T requiere bloque Tercero.",
                ["1187"] = "Bloque Tercero sólo si EmitidaPorTercerosODestinatario=T.",
                ["1188"] = "NIF Tercero debe ser distinto al NIF ObligadoEmision.",
                ["1189"] = "TipoFactura F1,F3,R1,R2,R3,R4 requiere Destinatarios cumplimentado.",
                ["1190"] = "TipoFactura F2 o R5 no permite Destinatarios.",
                ["1191"] = "TipoFactura R3 solo admite NIF o IDType=07.",
                ["1192"] = "TipoFactura R2 solo admite NIF o IDType07 o02.",
                ["1193"] = "NIF Destinatarios debe estar identificado y distinto del NIF ObligadoEmision.",
                ["1194"] = "TipoImpositivo permitido solo para fecha operación/expedición (>=01/07/2022 y <=30/09/2024).",
                ["1195"] = "OperacionExenta o CalificacionOperacion: al menos uno obligatorio.",
                ["1196"] = "OperacionExenta y CalificacionOperacion no pueden coexistir.",
                ["1197"] = "CalificacionOperacion=S2 sólo con TipoFactura F1,F3,R1,R2,R3,R4.",
                ["1198"] = "CalificacionOperacion=S2 obliga TipoImpositivo=0 y CuotaRepercutida=0.",
                ["1199"] = "Impuesto IVA/IGIC/vacío y ClaveRegimen01 no permiten OperacionExenta E2,E3.",
                ["1200"] = "ClaveRegimen03: CalificacionOperacion debe ser S1.",
                ["1201"] = "ClaveRegimen04: CalificacionOperacion S2 o OperacionExenta.",
                ["1202"] = "ClaveRegimen06: TipoFactura no puede ser F2,F3,R5 y BaseImponibleACoste obligatoria.",
                ["1203"] = "ClaveRegimen07: OperacionExenta no puede ser E2,E3,E4,E5 ni CalificacionOperacion S2,N1,N2.",
                ["1205"] = "ClaveRegimen10: CalificacionOperacion N1, TipoFactura F1 y Destinatarios con NIF.",
                ["1206"] = "ClaveRegimen11: TipoImpositivo debe ser21%.",
                ["1207"] = "CuotaRepercutida distinta de0 sólo si CalificacionOperacion S1.",
                ["1208"] = "CalificacionOperacion S1 y BaseImponibleACoste vacía: TipoImpositivo y CuotaRepercutida obligatorios.",
                ["1209"] = "CalificacionOperacion S1 y ClaveRegimen06: TipoImpositivo y CuotaRepercutida obligatorios.",
                ["1210"] = "ImporteTotal incorrecto respecto a BaseImponible, CuotaRepercutida y Recargo.",
                ["1211"] = "Bloque Tercero no puede tener IDType=07.",
                ["1212"] = "TipoUsoPosibleSoloVerifactu solo N o S.",
                ["1213"] = "TipoUsoPosibleMultiOT solo N o S.",
                ["1214"] = "NumeroOTAlta debe ser numérico positivo de4 posiciones.",
                ["1215"] = "Error en bloque ObligadoEmision.",
                ["1216"] = "CuotaTotal incorrecta respecto a CuotaRepercutida y Recargo.",
                ["1217"] = "Error identificando IDEmisorFactura.",
                ["1218"] = "Impuesto incorrecto.",
                ["1219"] = "IDEmisorFactura incorrecto.",
                ["1220"] = "NombreSistemaInformatico incorrecto.",
                ["1221"] = "IDType sistema informático incorrecto.",
                ["1222"] = "ID del bloque IDOtro incorrecto.",
                ["1223"] = "En SistemaInformatico se debe cumplimentar NIF o IDOtro, exactamente uno.",
                ["1224"] = "GeneradoPor requiere bloque Generador y viceversa.",
                ["1225"] = "GeneradoPor incorrecto.",
                ["1226"] = "IndicadorMultiplesOT solo N o S.",
                ["1227"] = "GeneradoPor=E requiere NIF en Generador.",
                ["1228"] = "Bloque Generador: NIF o IDOtro obligatorio (uno).",
                ["1229"] = "GeneradoPor=T: IDType Generador no debe ser07.",
                ["1230"] = "GeneradoPor=D y CodigoPais=ES: IDType debe ser03 o07.",
                ["1231"] = "IDType del bloque Generador incorrecto.",
                ["1232"] = "IDOtro CodigoPais=ES: IDType debe ser Pasaporte (03).",
                ["1233"] = "IDOtro CodigoPais=ES: IDType debe ser No Censado (07).",
                ["1234"] = "IDOtro CodigoPais=ES: IDType debe ser03 o07.",
                ["1235"] = "TipoImpositivo permitido sólo para rango01/10/2024-31/12/2024.",
                ["1236"] = "TipoImpositivo permitido sólo para rango01/10/2024-31/12/2024.",
                ["1237"] = "CalificacionOperacion N1/N2 e Impuesto IVA: no informar TipoImpositivo, CuotaRepercutida, Recargo.",
                ["1238"] = "Operación exenta: no informar TipoImpositivo, CuotaRepercutida ni Recargo.",
                ["1239"] = "Error en bloque Destinatario.",
                ["1240"] = "Error en bloque IdEmisorFactura.",
                ["1241"] = "Error técnico al obtener SistemaInformatico.",
                ["1242"] = "No existe el sistema informático.",
                ["1243"] = "Error técnico cálculo fecha huso horario.",
                ["1244"] = "FechaHoraHusoGenRegistro formato incorrecto.",
                ["1245"] = "Impuesto IVA(01)/IGIC(03)/vacío requiere ClaveRegimen cumplimentado.",
                ["1246"] = "ClaveRegimen incorrecto.",
                ["1247"] = "TipoHuella incorrecto.",
                ["1248"] = "Periodo incorrecto.",
                ["1249"] = "IndicadorRepresentante incorrecto.",
                ["1250"] = "Fecha desde debe ser menor que fecha hasta en RangoFechaExpedicion.",
                ["1251"] = "IdVersion incorrecto.",
                ["1252"] = "ClaveRegimen08 requiere CalificacionOperacion=N2 informado.",
                ["1253"] = "RefExterna incorrecto.",
                ["1254"] = "Fecha <01/01/2021 no permite Identificación 'XI' NIF-IVA.",
                ["1255"] = "Fecha >=01/02/2021 no permite Identificación 'GB' NIF-IVA.",
                ["1256"] = "Error técnico límite fecha expedición.",
                ["1257"] = "BaseImponibleACoste sólo si ClaveRegimen=06 o Impuesto=02 (IPSI) o Impuesto=05 (Otros).",
                ["1258"] = "NIF Generador incorrecto.",
                ["1259"] = "NIF Generador debe ser distinto del NIF ObligadoEmision y estar identificado.",
                ["1260"] = "ClaveRegimen sólo si Impuesto vacío/IVA(01)/IGIC(03).",
                ["1261"] = "IndicadorRepresentante sólo si consulta por ObligadoEmision.",
                ["1262"] = "Longitud de huella incorrecta.",
                ["1263"] = "Longitud de tipo de huella incorrecta.",
                ["1264"] = "Longitud del campo primer Registro incorrecta.",
                ["1265"] = "Longitud del campo tipo factura incorrecta.",
                ["1266"] = "Longitud del campo cuota total incorrecta.",
                ["1267"] = "Longitud del campo importe total incorrecta.",
                ["1268"] = "Longitud FechaHoraHusoGenRegistro incorrecta.",
                ["1269"] = "Bloque Registro Anterior no informado correctamente.",
                ["1270"] = "MostrarNombreRazonEmisor incorrecto.",
                ["1271"] = "MostrarSistemaInformatico incorrecto.",
                ["1272"] = "Consulta por Destinatario: MostrarSistemaInformatico debe ser 'N' o vacío.",
                ["1273"] = "Error en bloque Generador.",
                ["1274"] = "Valor incorrecto campo primer registro.",
                ["1275"] = "Valor incorrecto campo RechazoPrevio.",
                ["1276"] = "Valor incorrecto campo SinRegistroPrevio.",
                ["1277"] = "TipoRecargoEquivalencia incorrecto para tipo impositivo0%.",
                ["1278"] = "Huella registro anterior debe ser distinta de huella actual.",
                ["1281"] = "TipoRecargoEquivalencia y CuotaRecargoEquivalencia sólo si CalificacionOperacion S1.",
                ["1282"] = "NIF cabecera persona física requiere NombreRazon.",
                ["1283"] = "NIF contraparte persona física requiere NombreRazon.",
                ["1284"] = "TipoRecargoEquivalencia requiere CuotaRecargoEquivalencia y viceversa.",
                ["1285"] = "Varios Sistemas Informáticos encontrados; refine filtros.",
                ["1286"] = "Impuesto IVA(01)/IGIC(03)/vacío y ClaveRegimen02 sólo permite OperacionExenta.",
                ["1287"] = "Campo contiene caracteres no válidos (<, >, \" , ', =).",
                ["1288"] = "Error técnico validación fecha expedición/operación.",
                ["1289"] = "Impuesto IVA(01) o vacío y OperacionExenta=E5: sólo agrupación IDOtro en Destinatario.",
                ["3000"] = "Registro de facturación duplicado.",
                ["3001"] = "El registro de facturación ya ha sido dado de baja.",
                ["3002"] = "No existe el registro de facturación.",
                ["3003"] = "Presentador sin permisos para actualizar registro.",
                ["3004"] = "Factura dada de alta vía formulario; no modificable.",
                ["2000"] = "El cálculo de la huella suministrada es incorrecta.",
                ["2001"] = "NIF Destinatarios no identificado en censo AEAT.",
                ["2002"] = "Longitud huella registro anterior incorrecta.",
                ["2003"] = "Contenido huella registro anterior incorrecto.",
                ["2004"] = "FechaHoraHusoGenRegistro debe ser fecha actual AEAT (margen permitido).",
                ["2005"] = "ImporteTotal incorrecto respecto a BaseImponible, CuotaRepercutida y Recargo.",
                ["2006"] = "CuotaTotal incorrecta respecto a CuotaRepercutida y Recargo.",
                ["2007"] = "No debe marcarse como primer registro; existen facturas previas.",
                ["2008"] = "Huella registro anterior debe ser distinta de huella actual.",
            };
    }
}